version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: deploymentscripts/serviceapp.bash
      runas: root
  ApplicationStart:
    - location: deploymentscripts/startapp.bash
      runas: ubuntu
